version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: .docker/$NODE_ENV/api.dockerfile
    environment:
      NODE_ENV: $NODE_ENV
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
